ee_tys_default:
    resource: "@EETYSBundle/Resources/config/routing/default.yml"
    prefix: /

ee_tys_story:
    type: rest
    resource: "@EETYSBundle/Resources/config/routing/story.yml"
    prefix: /

