EETYSBundle_default:
    resource: "@EETYSBundle/Resources/config/routing/default.yml"
    prefix: /

EETYSBundle_api:
    type: rest
    resource: "@EETYSBundle/Resources/config/routing/api.yml"
    prefix: /api

EETYSBundle_story:
    resource: "@EETYSBundle/Resources/config/routing/story.yml"
    prefix:   /story


