parameters:
    eetys.form.type.audio.class: EE\TYSBundle\Form\AudioItemType
    eetys.form.type.file.class:  EE\TYSBundle\Form\FileItemType
    eetys.form.type.text.class:  EE\TYSBundle\Form\TextItemType
    eetys.form.type.url.class:   EE\TYSBundle\Form\UrlItemType
    eetys.form.type.video.class: EE\TYSBundle\Form\VideoItemType

services:
    ee_tys.story_voter:
        class: EE\TYSBundle\Security\Authorization\Voter\StoryVoter
        arguments: [@service_container]
        public: false
        tags:
          - { name: security.voter }

    ee_tys.voter_listener:
        class: EE\TYSBundle\EventListener\VoterListener
        arguments: [@service_container]
        tags:
          - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: -128  }

    liip_imagine.data.loader.stream.uploads:
        class: "%liip_imagine.data.loader.stream.class%"
        arguments:
            - "@liip_imagine"
            - 'data://uploads/'
        tags:
            - { name: 'liip_imagine.data.loader', loader: 'stream.uploads' }

    ee_tys.form.type.audio:
        class: "%eetys.form.type.audio.class%"
        tags:
            - { name: form.type, alias: ee_tysbundle_audioitemtype }

    ee_tys.form.type.file:
        class: "%eetys.form.type.file.class%"
        tags:
            - { name: form.type, alias: ee_tysbundle_fileitemtype }

    ee_tys.form.type.text:
        class: "%eetys.form.type.text.class%"
        tags:
            - { name: form.type, alias: ee_tysbundle_textitemtype }

    ee_tys.form.type.url:
        class: "%eetys.form.type.url.class%"
        tags:
            - { name: form.type, alias: ee_tysbundle_urlitemtype }

    ee_tys.form.type.video:
        class: "%eetys.form.type.video.class%"
        tags:
            - { name: form.type, alias: ee_tysbundle_videoitemtype }
