parameters:
    ee_tys.form.type.story.class: EE\TYSBundle\Form\StoryType
    ee_tys.form.type.image.class: EE\TYSBundle\Form\ImageItemType
    ee_tys.form.type.audio.class: EE\TYSBundle\Form\AudioItemType
    ee_tys.form.type.file.class:  EE\TYSBundle\Form\FileItemType
    ee_tys.form.type.text.class:  EE\TYSBundle\Form\TextItemType
    ee_tys.form.type.url.class:   EE\TYSBundle\Form\UrlItemType
    ee_tys.form.type.video.class: EE\TYSBundle\Form\VideoItemType
    ee_tys.user_provider.class:   EE\TYSBundle\Security\Core\User\TYSUserProvider
    ee_tys.user_provider.class:  EE\TYSBundle\Security\Core\User\TYSUserProvider
    ee_tys.entity.user.class:    EE\TYSBundle\Entity\User
    ee_tys.story_voter.class:    EE\TYSBundle\Security\Authorization\Voter\StoryVoter
    ee_tys.item_voter.class:     EE\TYSBundle\Security\Authorization\Voter\ItemVoter
    ee_tys.story_collection_voter.class:     EE\TYSBundle\Security\Authorization\Voter\StoryCollectionVoter

services:
    ee_tys.user_provider:
        class: "%ee_tys.user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: ["@ee_light_user.user_manager"]

    ee_tys.story_voter:
        class: "%ee_tys.story_voter.class%"
        arguments: [@service_container]
        public: false
        tags:
          - { name: security.voter }

    ee_tys.item_voter:
        class: "%ee_tys.item_voter.class%"
        arguments: [@service_container]
        public: false
        tags:
          - { name: security.voter }

    ee_tys.story_collection_voter:
        class: "%ee_tys.story_collection_voter.class%"
        arguments: [@service_container]
        public: false
        tags:
          - { name: security.voter }
#    ee_tys.voter_listener:
#        class: EE\TYSBundle\EventListener\VoterListener
#        arguments: [@service_container]
#        tags:
#          - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: -128  }

    ee_tys.doctrine.item_subscriber:
        class: EE\TYSBundle\EventListener\Doctrine\ItemSubscriber
        arguments:
            - "@service_container"
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    liip_imagine.data.loader.stream.uploads:
        class: "%liip_imagine.data.loader.stream.class%"
        arguments:
            - "@liip_imagine"
            - 'data://uploads/'
        tags:
            - { name: 'liip_imagine.data.loader', loader: 'stream.uploads' }

    ee_tys.serializer.filename_handler:
        class: EE\TYSBundle\Handler\FilenameHandler
        arguments:
            - "@liip_imagine.cache.manager"
        tags:
            - { name: 'jms_serializer.handler', type: Filename, format: json}

    ee_tys.form.type.story:
        class: "%ee_tys.form.type.story.class%"
        arguments:
            - "@validator"
        tags:
            - { name: form.type, alias: ee_tysbundle_storytype }

    ee_tys.form.type.image:
        class: "%ee_tys.form.type.image.class%"
        arguments:
            - "@validator"
        tags:
            - { name: form.type, alias: ee_tysbundle_imageitemtype }

    ee_tys.form.type.audio:
        class: "%ee_tys.form.type.audio.class%"
        arguments:
            - "@validator"
        tags:
            - { name: form.type, alias: ee_tysbundle_audioitemtype }

    ee_tys.form.type.file:
        class: "%ee_tys.form.type.file.class%"
        arguments:
            - "@validator"
        tags:
            - { name: form.type, alias: ee_tysbundle_fileitemtype }

    ee_tys.form.type.text:
        class: "%ee_tys.form.type.text.class%"
        tags:
            - { name: form.type, alias: ee_tysbundle_textitemtype }

    ee_tys.form.type.url:
        class: "%ee_tys.form.type.url.class%"
        tags:
            - { name: form.type, alias: ee_tysbundle_urlitemtype }

    ee_tys.form.type.video:
        class: "%ee_tys.form.type.video.class%"
        tags:
            - { name: form.type, alias: ee_tysbundle_videoitemtype }
