<?php

namespace EE\TYSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StoryCollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoryCollectionRepository extends EntityRepository
{
}
