eetys_default_homepage:
    pattern:  /
    defaults: { _controller: EETYSBundle:Default:homepage }

eetys_default_logout:
    pattern: /logout
    defaults: { _controller: EETYSBundle:Default:homepage }

