fileitem:
    pattern:  /
    defaults: { _controller: "EETYSBundle:FileItem:index" }

fileitem_show:
    pattern:  /{id}/show
    defaults: { _controller: "EETYSBundle:FileItem:show" }

fileitem_new:
    pattern:  /new
    defaults: { _controller: "EETYSBundle:FileItem:new" }

fileitem_create:
    pattern:  /create
    defaults: { _controller: "EETYSBundle:FileItem:create" }
    requirements: { _method: post }

fileitem_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EETYSBundle:FileItem:edit" }

fileitem_update:
    pattern:  /{id}/update
    defaults: { _controller: "EETYSBundle:FileItem:update" }
    requirements: { _method: post|put }

fileitem_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EETYSBundle:FileItem:delete" }
    requirements: { _method: post|delete }
