item:
    pattern:  /
    defaults: { _controller: "EETYSBundle:Item:index" }

item_show:
    pattern:  /{id}/show
    defaults: { _controller: "EETYSBundle:Item:show" }

item_select_type:
    pattern:  /{storyId}/select-type
    defaults: { _controller: "EETYSBundle:Item:selectType" }

item_new:
    pattern:  /{storyId}/{type}/new
    defaults: { _controller: "EETYSBundle:Item:new" }
    requirements:
        type:    audio|image|text|url|video

item_create:
    pattern:  /{storyId}/{type}/create
    defaults: { _controller: "EETYSBundle:Item:create" }
    requirements:
        _method: post
        type:    audio|image|text|url|video

item_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EETYSBundle:Item:edit" }

item_update:
    pattern:  /{id}/update
    defaults: { _controller: "EETYSBundle:Item:update" }
    requirements: { _method: post|put }

item_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EETYSBundle:Item:delete" }
    requirements: { _method: post|delete }
