story:
    pattern:  /
    defaults: { _controller: "EETYSBundle:Story:index" }

story_by_user:
    pattern:  /by/{id}
    defaults: { _controller: "EETYSBundle:Story:index" }
    requirements:
        id: "\d+"

story_show:
    pattern:  /{id}/show
    defaults: { _controller: "EETYSBundle:Story:show" }
    options: {expose: true}

story_new:
    pattern:  /new
    defaults: { _controller: "EETYSBundle:Story:new" }

story_create:
    pattern:  /create
    defaults: { _controller: "EETYSBundle:Story:create" }
    requirements: { _method: post }

story_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EETYSBundle:Story:edit" }

story_update:
    pattern:  /{id}/update
    defaults: { _controller: "EETYSBundle:Story:update" }
    requirements: { _method: post|put }

story_publish:
    pattern:  /{id}/publish
    defaults: { _controller: "EETYSBundle:Story:publish" }

story_preview:
    pattern:  /{id}/preview
    defaults: { _controller: "EETYSBundle:Story:preview" }

story_set_coeditability:
    pattern:  /{id}/colaborate/{isCoeditable}
    defaults: { _controller: "EETYSBundle:Story:setCoeditability" }
    requirements:
        isCoeditable: "[0,1]"


story_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EETYSBundle:Story:delete" }
    requirements: { _method: post|delete }
